Oshell issue 6 fix
karaggeorge/electron-builder-notarize pull request #8
Opened 2020-05-26 18:51 UTC by oshell

2020-07-01 17:07 UTC, krzysztof-jelski requested changes
As I'm interested in having this PR merged, I left a couple of comments that should help make the linter happy. Also, with the suggestion to use `params.outDir`, it should be applicable for all builds, not only the vue plugin.

2020-07-01 17:07 UTC, krzysztof-jelski commented on index.js
> +const fs = require('fs');
Move above line 4.

2020-07-01 17:07 UTC, krzysztof-jelski commented on index.js
> +		appId = buildConfig.appId;
Actually, the `builder-effective-config.yaml` is created always, even if the config is done from `package.json`. So we don't need this whole first branch of the `if`.

2020-07-01 17:07 UTC, krzysztof-jelski commented on index.js
> +			const path = './dist_electron/builder-effective-config.yaml'
```suggestion
			const path = path.join(params.outDir, 'builder-effective-config.yaml');
```

2020-07-01 17:07 UTC, krzysztof-jelski commented on index.js
> +			// fallback for vue-cli-plugin-electron-builder
I suggest to remove the comment, as it's relevant not only to the vue plugin, but to all cases when electron config is done outside package.json.

2020-07-01 17:07 UTC, krzysztof-jelski commented on index.js
> +			if (fs.existsSync(path)) {
Remove this check. I believe this file is always present in an electron build, so throwing if it's not should be ok.

2020-07-01 17:07 UTC, krzysztof-jelski commented on index.js
> +	let appId = '';
Perhaps it's worth to extract the new code to function `readAppId`.

2020-07-01 17:07 UTC, krzysztof-jelski commented on index.js
> +		} catch(err) {
If you agree to leave this way as the only one of finding the appId, then we should throw instead of console logging.

2020-07-01 17:07 UTC, krzysztof-jelski commented on index.js
> +			console.error(err)
```suggestion
			console.error(err);
```

2020-07-01 17:07 UTC, krzysztof-jelski commented on index.js
> +		} catch(err) {
```suggestion
		} catch (error) {
```

2020-07-01 17:07 UTC, krzysztof-jelski commented on index.js
> +				let data = yaml.safeLoad(fileContents);
```suggestion
				const data = yaml.safeLoad(fileContents);
```

2020-07-01 17:07 UTC, krzysztof-jelski commented on index.js
> +				let fileContents = fs.readFileSync(path, 'utf8');
```suggestion
				const fileContents = fs.readFileSync(path, 'utf8');
```

2020-07-01 17:13 UTC, karaggeorge commented
@oshell would you be interested in finishing this? Making the changes listed above by @krzysztof-jelski ?

Just make sure `yarn test` passes before pushing and I can merge this

2020-07-09 13:36 UTC, ruudboon commented
Any updates on this? If it's only implementing the suggestions of @krzysztof-jelski I won't mind taking over and dropping a pull with those changes.

2020-07-09 13:41 UTC, karaggeorge commented
Hey @ruudboon ,

I think I'm just going to apply the needed changes locally and publish a release. I'll update here when it's ready and close this

2020-07-09 13:42 UTC, ruudboon commented
@karaggeorge Awesome, thnx. Then I will close my fork ;) :D

2020-07-09 14:13 UTC, karaggeorge commented
@ruudboon can you check #9

2020-07-09 15:10 UTC, closed without merging